//
//  AvatarView.swift
//  BezierPathRealWorldExample
//
//  Created by Gokhan Gultekin on 11.11.2018.
//  Copyright © 2018 Gokhan. All rights reserved.
//

import UIKit

class AvatarView: UIView {

    override func awakeFromNib() {
        backgroundColor = UIColor.clear
    }

    override func draw(_ rect: CGRect) {
        // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
        // http://www.paintcodeapp.com
        
        //// Color Declarations
        let fillColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        
        //// iPhone_6_7_8_1
        //// Rectangle Drawing
        
        //// Subtraction_1 Drawing
        let subtraction_1Path = UIBezierPath()
        subtraction_1Path.move(to: CGPoint(x: 254, y: 116))
        subtraction_1Path.addLine(to: CGPoint(x: -0, y: 116))
        subtraction_1Path.addCurve(to: CGPoint(x: 25.18, y: 107.22), controlPoint1: CGPoint(x: 10.5, y: 115.99), controlPoint2: CGPoint(x: 18.97, y: 113.03))
        subtraction_1Path.addLine(to: CGPoint(x: 25.27, y: 107.14))
        subtraction_1Path.addCurve(to: CGPoint(x: 34.55, y: 88.91), controlPoint1: CGPoint(x: 30.31, y: 102.27), controlPoint2: CGPoint(x: 33.58, y: 95.85))
        subtraction_1Path.addLine(to: CGPoint(x: 34.6, y: 88.03))
        subtraction_1Path.addCurve(to: CGPoint(x: 132.27, y: 0.09), controlPoint1: CGPoint(x: 37.29, y: 36.78), controlPoint2: CGPoint(x: 81.02, y: -2.59))
        subtraction_1Path.addCurve(to: CGPoint(x: 220.27, y: 89.65), controlPoint1: CGPoint(x: 180.38, y: 2.62), controlPoint2: CGPoint(x: 218.59, y: 41.5))
        subtraction_1Path.addLine(to: CGPoint(x: 220.24, y: 88.91))
        subtraction_1Path.addCurve(to: CGPoint(x: 229.52, y: 107.13), controlPoint1: CGPoint(x: 221.22, y: 95.85), controlPoint2: CGPoint(x: 224.48, y: 102.26))
        subtraction_1Path.addCurve(to: CGPoint(x: 254, y: 115.99), controlPoint1: CGPoint(x: 235.72, y: 112.9), controlPoint2: CGPoint(x: 243.9, y: 115.83))
        subtraction_1Path.addLine(to: CGPoint(x: 254, y: 116))
        subtraction_1Path.close()
        fillColor.setFill()
        subtraction_1Path.fill()

    }
}
